/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import controladores.ControlSorteo;
import identidades.Administracion;
import identidades.Billete;
import javax.swing.JOptionPane;

/**
 *
 * @author ASANCOR
 */
public class VentanaSorteos extends javax.swing.JDialog {

    public static ControlSorteo cs;

    /**
     * Creates new form VentanaSorteos
     */
    public VentanaSorteos(java.awt.Frame parent, boolean modal, ControlSorteo cs) {
        super(parent, modal);
        initComponents();
        this.cs = cs;
        rellenarComboAdministracion();
        rellenarComboBilletes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAsignarBilletes = new javax.swing.JButton();
        comboAdministraciones = new javax.swing.JComboBox<>();
        comboBilletes = new javax.swing.JComboBox<>();
        txtNSeries = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSorteo = new javax.swing.JTextArea();
        btnRealizarSorteo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnAsignarBilletes.setText("Asignar Billetes");
        btnAsignarBilletes.setToolTipText("");
        btnAsignarBilletes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarBilletesActionPerformed(evt);
            }
        });

        comboAdministraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAdministracionesActionPerformed(evt);
            }
        });

        comboBilletes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBilletesActionPerformed(evt);
            }
        });

        txtNSeries.setText("1");

        txtSorteo.setColumns(20);
        txtSorteo.setRows(5);
        txtSorteo.setText("Comenzando nuevo sorteo...\n");
        jScrollPane1.setViewportView(txtSorteo);

        btnRealizarSorteo.setText("Realizar Sorteo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRealizarSorteo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(btnAsignarBilletes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(comboAdministraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBilletes, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNSeries, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNSeries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboBilletes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboAdministraciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAsignarBilletes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRealizarSorteo, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboAdministracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAdministracionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAdministracionesActionPerformed

    private void btnAsignarBilletesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarBilletesActionPerformed
        cs.asignarBilletes((Administracion)comboAdministraciones.getSelectedItem(), (Billete)comboBilletes.getSelectedItem(), Integer.parseInt(txtNSeries.getText()));
    }//GEN-LAST:event_btnAsignarBilletesActionPerformed

    private void comboBilletesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBilletesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBilletesActionPerformed

    private void rellenarComboAdministracion() {
        Administracion aAdministraciones[] = cs.obtenerComboAdministraciones();
        comboAdministraciones.removeAllItems();
        for (int i = 0; i < aAdministraciones.length; i++) {
            comboAdministraciones.addItem(aAdministraciones[i]);
        }
    }

    private void rellenarComboBilletes() {
        Billete aBilletes[] = cs.obtenerComboBilletes();
        comboBilletes.removeAllItems();
        for (int i = 0; i < aBilletes.length; i++) {
            comboBilletes.addItem(aBilletes[i]);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSorteos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSorteos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSorteos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSorteos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaSorteos dialog = new VentanaSorteos(new javax.swing.JFrame(), true, cs);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarBilletes;
    private javax.swing.JButton btnRealizarSorteo;
    private javax.swing.JComboBox<Administracion> comboAdministraciones;
    private javax.swing.JComboBox<Billete> comboBilletes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtNSeries;
    private javax.swing.JTextArea txtSorteo;
    // End of variables declaration//GEN-END:variables
}
